fix AutoLoginToken serialization
jmikola/AutoLogin pull request #22
Opened 2020-11-26 14:21 UTC by ezprit

This PR fixes AutoLoginToken serialization for symfony/security-core > 4.3

https://github.com/symfony/security-core/commit/f948fedde6c1b86d9a8b16d8016ce3376be20f74

2020-12-21 07:33 UTC, jmikola requested changes
Sorry for the delayed review. I have one question on a possible change before merging.

2020-12-21 07:33 UTC, jmikola commented on src/Jmikola/AutoLogin/Authentication/Token/AutoLoginToken.php
> +        $parentData = \is_array($parentData) ? $parentData : unserialize($parentData);
Quoting https://github.com/symfony/security-core/commit/f948fedde6c1b86d9a8b16d8016ce3376be20f74#diff-c5e43b78aa0cd524bf4965e55c5839b0e4eebc0afde1fd0ba45deb946d1734d9R187:

> There is no need to unserialize any entry in $data, they are already ready-to-use.

In that case, would you agree that this line is redundant and should be removed?

2020-12-21 07:33 UTC, jmikola commented on src/Jmikola/AutoLogin/Authentication/Token/AutoLoginToken.php
> +        return [$this->key, $this->providerKey, parent::__serialize()];
This matches the example provided in https://github.com/symfony/security-core/commit/f948fedde6c1b86d9a8b16d8016ce3376be20f74#diff-c5e43b78aa0cd524bf4965e55c5839b0e4eebc0afde1fd0ba45deb946d1734d9R145, so I trust it's correct.

2021-02-10 08:07 UTC, atiernan commented
I'm also experiencing this issue. Is there any chance you could check over this PR @jmikola?

2021-02-17 10:25 UTC, merged

2021-02-17 10:26 UTC, jmikola commented
Merged and released as [2.0.1](https://github.com/jmikola/AutoLogin/releases/tag/2.0.1).